install

diff --git a/09_install b/09_install
--- a/09_install
+++ b/09_install
@@ -9,6 +9,17 @@ if [ $USERID -ne 0 ]; then
      
 fi
 
+# first arg  -> what are you trying to install
+# second arg  -> exit code
+VALIDATE(){
+      if [ $2 -ne 0]; then
+      echo "Installing $1 is ... Failed"
+      exit 1
+    else
+      echo "Installing $1 is ... SUCCESS"
+    fi   
+}
+
 dnf list installed mysql
 
 if [ $? -eq 0 ]; then
@@ -16,12 +27,15 @@ if [ $? -eq 0 ]; then
 else
      echo "Installing MySQL"
      dnf install mysql -y
-
-
-    if [ $? -ne 0 ]; then
-         echo "Installing MySQL is   .... FAILED"
-        exit 1
-    else 
-        echo "Install Mysql is .. SUCCESS"
-   fi
+     VALIDATE MySQL $?
 fi
+
+dnf list installed nginx
+if [ $? -eq 0 ]; then
+    echo "nginx is already installed ... SKIPPING"
+else
+    echo "Installing nginx"
+    dnf install nginx -y
+    VALIDATE nginx $?
+fi
+
