install

diff --git a/09_install b/09_install
--- a/09_install
+++ b/09_install
@@ -3,7 +3,7 @@
 USERID=$(id -u)
 
 #check root access or not
-if [ $USERID -ne 0]; then
+if [ $USERID -ne 0 ]; then
      echo "Please run this script with root access"
      exit 1
      
@@ -13,8 +13,8 @@ echo "Installing MySQL"
 dnf install mykhsql -y
 
 
-if [$? -ne 0]; then
-echo "Installing MySql is   .... FAILED"
+if [ $? -ne 0 ]; then
+echo "Installing MySQL is   .... FAILED"
 exit 1
 else 
 echo "Install Mysql is .. SUCCESS"
