install

diff --git a/09_install b/09_install
--- a/09_install
+++ b/09_install
@@ -9,13 +9,19 @@ if [ $USERID -ne 0 ]; then
      
 fi
 
-echo "Installing MySQL"
-dnf install mysql -y
+dnf list installed mysql
+
+if [ $? -eq 0 ]; then
+     echo "MySQL is already installed ... SKIPPING"
+else
+     echo "Installing MySQL"
+     dnf install mysql -y
 
 
-if [ $? -ne 0 ]; then
-echo "Installing MySQL is   .... FAILED"
-exit 1
-else 
-echo "Install Mysql is .. SUCCESS"
+    if [ $? -ne 0 ]; then
+         echo "Installing MySQL is   .... FAILED"
+        exit 1
+    else 
+        echo "Install Mysql is .. SUCCESS"
+   fi
 fi
